### ISSUE TITLE
Error: router.route is not a function

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#82]
## Describe the problem

Running the server results in the error
```
TypeError: router.route(...).delete(...).patch(...).get(...).route is not a function
    at Object.<anonymous> (F:\Programming\teamwork-be\src\routes\posts.js:331:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\Programming\teamwork-be\src\routes\index.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
```

## Actual behavior

A clear and concise description of what you experienced.
1. Pull the main branch and start the server with `npm run dev`
2. The error is logged in the terminal
## Expected behavior
The server should run successfully

## To Reproduce

1. Pull the main branch and start the server with `npm run dev`
2. The error is logged in the terminal
3. See error

**Comment by jakazzy** [comment]
From investigating, it seems this may have resulted from earlier merge conflicts that were resolved. This led to duplication of the routes.
